name: Output Issue Details workflow
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  Output_issue_details_job:
    runs-on: ubuntu-latest
    steps:
      - name: Output_issue_details_step
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue User: ${{ github.event.issue.user.login }}"

# added this line to check if "git push" command executed on a branch in local git repo
# will push that change to the same branch in remote repo.
