name: Output Issue Details workflow
on: issue
jobs:
  Output issue details job:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue details step
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue User: ${{ github.event.issue.user.login }}"
